# -*- coding: utf-8 -*-
"""allgorometiveclustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNUS4Rahdu7Ee_dMdM9enX5epr6fUaTc
"""

from google.colab import drive
import pandas as pd


drive.mount('/content/drive')


df = pd.read_csv('/content/Mall_Customers.csv')
df.head()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import scipy.cluster.hierarchy as sch
x = df.iloc[:, [3,4]].values
dendrogram=sch.dendrogram(sch.linkage(x,method='ward'))
plt.title('dendogram')
plt.xlabel('customers')
plt.ylabel('Euclidian dist')
plt.show()

from sklearn.cluster import AgglomerativeClustering
hc=AgglomerativeClustering(n_clusters=5, metric='euclidean', linkage='ward')
y_hc=hc.fit_predict(x)
y_hc



from sklearn.metrics import silhouette_score
score=silhouette_score(x,y_hc)
score

import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download(
    "ankurzing/sentiment-analysis-for-financial-news"
)

print("Path to dataset files:", path)

print(os.listdir(path))

df = pd.read_csv(os.path.join(path, "all-data.csv"), header=None, encoding='latin1')

# Give column names
df.columns = ["sentiment", "news"]

df

from sklearn.preprocessing import LabelEncoder
df.isnull().sum()

le=LabelEncoder()
df['sentiment']=le.fit_transform(df['sentiment'])

df

x=df.iloc[]

# FULL COLAB CODE — AGGLOMERATIVE (DENDROGRAM)

!pip install kagglehub

import kagglehub
import pandas as pd
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

# Download dataset
path = kagglehub.dataset_download(
    "ankurzing/sentiment-analysis-for-financial-news"
)

# Load CSV
files = os.listdir(path)
csv_file = [f for f in files if f.endswith(".csv")][0]
df = pd.read_csv(os.path.join(path, csv_file), encoding='latin1')

# Take small sample (dendrogram needs limited data)
texts = df.iloc[:50, 0].astype(str)

# TF-IDF
vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(texts).toarray()

# Agglomerative linkage
Z = linkage(X, method="ward")

# Dendrogram
plt.figure(figsize=(14, 6))
dendrogram(Z)
plt.title("Agglomerative Hierarchical Clustering Dendrogram")
plt.xlabel("Data Points")
plt.ylabel("Distance")
plt.show()

