# -*- coding: utf-8 -*-
"""Untitled50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxQlUxTXe7UTNhm1T2pWU8gzwOdNCVuk
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import *

from google.colab import drive
import pandas as pd


drive.mount('/content/drive')


df = pd.read_csv('/content/Mall_Customers.csv')
df.head()

x=df.iloc[:, [3,4]].values

import matplotlib.pyplot as plt
plt.scatter(x[:,0], x[:,1])

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

from sklearn.cluster import DBSCAN
dbscan=DBSCAN(eps=0.3,min_samples=5)
clusters=dbscan.fit_predict(x)

plt.figure(figsize=(7,5))
plt.scatter(x[:,0], x[:,1])

from sklearn.metrics import silhouette_score
score=silhouette_score(x, clusters)
score



