# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBcUWhUwGvuVeZjBcKCV0OGKcQStLTj7
"""

from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()



df.head()

x=df[['Age','EstimatedSalary']]
y=df['Purchased']

df.isnull().sum()

df=df.drop(columns=['User ID'])

df.head()

x

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import *
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

df.head()

x_train

x_test

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=3,criterion="entropy")
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))

model2=DecisionTreeClassifier(max_depth=3,criterion="gini")
model2.fit(x_train,y_train)
y_pred2=model2.predict(x_test)
accuracy_score(y_test,y_pred2)

confusion_matrix(y_test,y_pred2)

print(classification_report(y_test,y_pred2))

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
plot_tree(
    model,
    feature_names=["Age","Estimated Salary"],
    class_names=["not purchased","purchased"],
    filled=True,
    rounded=True
)
plt.show()

"""# **New Section**
Titanic dataset using dtc using gini split

"""

import seaborn as sns
df1=sns.load_dataset("titanic")
df1.head()

df1.isnull().sum()

df1=df1[["survived","pclass","sex","age","fare","embarked"]]
df1.head()

df1['age'].fillna(df1['age'].median(),inplace=True)
df1['embarked'].fillna(df1['embarked'].mode()[0],inplace=True)

df1.head()

df1.isnull().sum()

df1['sex'].unique()

df1['embarked'].unique()

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
df1['sex']=le.fit_transform(df1['sex'])

df1['sex']

df1['embarked']=le.fit_transform(df1['embarked'])

df1.head()

x=df1.drop(columns=['survived'])
y=df1['survived']

x

y

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
sc1=StandardScaler()
x_train=sc1.fit_transform(x_train)
x_test=sc1.transform(x_test)
model=DecisionTreeClassifier(criterion='gini',max_depth=3)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))

passenger=[[3,1,25,7,2]]
print(model.predict(passenger))

import pandas as pd
new_passenger=pd.DataFrame([[3,1,25,7,2]],columns=x.columns)
print(model.predict(new_passenger))