# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcOLv-SO4e65H-0tGSHkeLRp5PxnEkN2
"""

from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

df = pd.read_csv('/content/bank_marketing_dataset.csv')
df.head()

for i in df.columns:
    print(f"for {i}")

    print(df[i].unique())
    print(df[i].nunique())
    print("\n")

from sklearn.preprocessing import StandardScaler,LabelEncoder
le=LabelEncoder()
lst=['contact','poutcome','job','marital','education','default','housing','loan','month']
for x in lst:
  df[x]=le.fit_transform(df[x])

df.head()

x=df.drop(columns=['deposit'])
y=df['deposit']

x

y

df['deposit']=le.fit_transform(df['deposit'])

y

y=df['deposit']

y

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
model=DecisionTreeClassifier(criterion='gini',max_depth=5)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import *

accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

print(classification_report(y_test,y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

numeric_cols = df.select_dtypes(include=['int64','float64']).columns
print(numeric_cols)
sns.boxplot(x='deposit', y='age', data=df)
plt.title("Balance Distribution by Deposit")
plt.show()

sns.boxplot(x='deposit', y='balance', data=df)
plt.title("Balance Distribution by Deposit")
plt.show()