# -*- coding: utf-8 -*-
"""feature_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J7uk0XBXxwdXmsa2wkX2itrzypoWuQz2
"""

import pandas as pd
import seaborn as sns
df=sns.load_dataset("taxis")
df

df.columns

df.shape

df.describe(

)

df.info(

)

df.describe(include="object")

df.describe(include="all")

df.duplicated

df.isnull(

)

df.isnull().sum()

df=df.drop_duplicates()

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

df.shape

df.reset_index(drop=True)

df.color.value_counts()

sns.barplot(x=df.tip,y=df.color,estimator='std',palette={'yellow':'yellow','green':'green'})

df.describe()

sns.histplot(data=df, x=df['tip'], hue='color', kde=True,palette={'yellow':'yellow','green':'green'})





import matplotlib.pyplot as plt
import seaborn as sns

correlation_matrix = df.corr(numeric_only=True)

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".3f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

male_income=data[data['gender'=='male']]

yellow_tip=df['tip'][df['color']=='yellow']
green_tip=df['tip'][df['color']=='green']
yellow_tip

green_tip

# T test
from scipy import stats
tval,pval=stats.ttest_ind(yellow_tip,green_tip)
print("tval=",tval,"pval=",pval)
if pval<0.05:
    print("we reject null hypothesis")
else:
    print("we accept null hypothesis")

"""Ho=  tip through credit card and cash payment are different
H1=No significance difference between credit card and cash payment
"""

credit_card_tip=df['tip'][df['payment']=='credit card']
cash_tip=df['tip'][df['payment']=='cash']

# T test
from scipy import stats
tval,pval=stats.ttest_ind(yellow_tip,green_tip)
print("tval=",tval,"pval=",pval)
if pval<0.05:
    print("we reject null hypothesis")
else:
    print("we accept null hypothesis")

sns.barplot(x=df.payment,y=df.tip,estimator='std',palette={'credit card':'skyblue','cash':'red'})
plt.title('std Tip Distribution by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Tip Amount')
plt.show()

sns.barplot(x=df.payment,y=df.tip,estimator='std',palette={'credit card':'skyblue','cash':'red'})
plt.title(' mean Tip Distribution by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Tip Amount')
plt.show()

sns.histplot(data=df, x=df['tip'], hue='payment', kde=True)

df.columns

df['pickup_borough'].value_counts()

sns.countplot(x=df['pickup_borough'],palette="Set2")

sns.barplot(x=df.pickup_borough,y=df.tip,data=df,estimator='std',palette="Set2")



sns.histplot( data=df,x=df['tip'], hue='pickup_borough', kde=True,bins=30)
plt.show()

"""Ho=ditribution of tips across all pickup_borrough categories is same
H1=atleast one category is diffrerent
"""

manhattan_tips = df[df['pickup_borough'] == 'Manhattan']['tip']
brooklyn_tips = df[df['pickup_borough'] == 'Brooklyn']['tip']
queens_tips = df[df['pickup_borough'] == 'Queens']['tip']
bronx_tips = df[df['pickup_borough'] == 'Bronx']['tip']
stat, p_value = stats.f_oneway(manhattan_tips, brooklyn_tips, queens_tips, bronx_tips)
print("F-statistic:", stat)
print("p-value:", p_value)
if p_value < 0.05:
    print("Reject the null hypothesis. There is a significant difference in tips across pickup_borough categories.")
else:
    print("Fail to reject the null hypothesis. There is no significant difference in tips across pickup_borough categories.")

from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Perform Tukey's HSD post-hoc test
tukey_result = pairwise_tukeyhsd(endog=df['tip'], groups=df['pickup_borough'], alpha=0.05)

print(tukey_result)

"""The output of the Tukey HSD test above shows pairwise comparisons between the mean tip amounts for each `pickup_borough`.

*   **`meandiff`**: The difference between the means of the two groups being compared.
*   **`p-adj`**: The adjusted p-value for the comparison. If `p-adj` < 0.05, the difference between the means is statistically significant.
*   **`lower`** and **`upper`**: The lower and upper bounds of the 95% confidence interval for the mean difference.
*   **`reject`**: Indicates whether the null hypothesis (that the means are equal) is rejected for that pair. If `True`, there's a significant difference.
"""

df['dropoff_borough'].value_counts()

sns.countplot(x=df['dropoff_borough'],palette="Set2")

sns.barplot(x=df.dropoff_borough,y=df.tip,data=df,estimator='std',palette="Set1")

#hypothesis testing
manhattan_tips = df[df['dropoff_borough'] == 'Manhattan']['tip']
brooklyn_tips = df[df['dropoff_borough'] == 'Brooklyn']['tip']
queens_tips = df[df['dropoff_borough'] == 'Queens']['tip']
bronx_tips = df[df['dropoff_borough'] == 'Bronx']['tip']
staten_island_tips = df[df['dropoff_borough'] == 'Staten Island']['tip']
stat, p_value = stats.f_oneway(manhattan_tips, brooklyn_tips, queens_tips, bronx_tips, staten_island_tips)
print("F-statistic:", stat)
print("p-value:", p_value)
if p_value<0.05:
  print("accept null")
else:
  print("reject null")

from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Perform Tukey's HSD post-hoc test
tukey_result = pairwise_tukeyhsd(endog=df['tip'], groups=df['dropoff_borough'], alpha=0.05)

print(tukey_result)

"""H0=correlatiion is zero
H1= there is significant correlation(not zero)
"""

r,p_val=stats.spearmanr(df['tip'],df['passengers'])
print("correlation",r)
print("p_value",p_val)
if p_val<0.05:
  print("reject null")
else:
  print("accept null")

sns.barplot(x=df.passengers,y=df.tip,data=df,estimator='std',palette="Set1")

sns.histplot(x=df['total'],kde=True)

r,p_val=stats.spearmanr(df['tip'],df['total'])
print("correlation",r)
print("p_value",p_val)
if p_val<0.05:
  print("reject null")
else:
  print("accept null")

r,p_val=stats.spearmanr(df['tip'],df['tolls'])
print("correlation",r)
print("p_value",p_val)
if p_val<0.05:
  print("reject null")
else:
  print("accept null")

from scipy import stats

r, p_val = stats.pearsonr(df['distance'], df['tip'])

print("PEARSON CORRELATION TEST")
print("Correlation:", r)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Distance has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Distance has no impact on tip")

from scipy.stats import spearmanr

r, p_val = spearmanr(df['fare'], df['tip'])

print("SPEARMAN CORRELATION TEST (fare_amount vs tip)")
print("Correlation:", r)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Fare amount has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Fare amount has no impact on tip")

from scipy.stats import spearmanr

r, p_val = spearmanr(df['total'], df['tip'])

print("SPEARMAN CORRELATION TEST (total vs tip)")
print("Correlation:", r)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Total amount has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Total amount has no impact on tip")

from scipy.stats import spearmanr

r, p_val = spearmanr(df['passengers'], df['tip'])

print("SPEARMAN CORRELATION TEST (passenger_count vs tip)")
print("Correlation:", r)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Passenger count has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Passenger count has no impact on tip")

from scipy.stats import ttest_ind

cash_tip = df[df['payment'] == 'cash']['tip']
card_tip = df[df['payment'] == 'credit card']['tip']

t_stat, p_val = ttest_ind(cash_tip, card_tip)

print("INDEPENDENT T-TEST (payment_type vs tip)")
print("t-statistic:", t_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Payment type has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Payment type has no impact on tip")

from scipy.stats import f_oneway

man = df[df['dropoff_borough'] == 'Manhattan']['tip']
que = df[df['dropoff_borough'] == 'Queens']['tip']
bro = df[df['dropoff_borough'] == 'Brooklyn']['tip']
bronx = df[df['dropoff_borough'] == 'Bronx']['tip']
staten_island = df[df['dropoff_borough'] == 'Staten Island']['tip']

f_stat, p_val = f_oneway(man, que, bro, bronx, staten_island)

print("ONE-WAY ANOVA (dropoff_borough vs tip)")
print("F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Dropoff borough has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Dropoff borough has no impact on tip")

from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(
    endog=df['tip'],
    groups=df['dropoff_borough'],
    alpha=0.05
)

print("TUKEY HSD RESULT")
print(tukey)

df.info()

#analysis on datetime

df['pickup']

df['pickup'].dt.day

df['pickup'].dt.month

df['pickup'].dt.month_name()

df['pickup'].dt.year

df['pickup'].dt.day_name()

df['dropoff_month']=df['dropoff'].dt.month_name()

df['dropoff_year']=df['dropoff'].dt.year

df['dropoff_dayname']=df['dropoff'].dt.day_name()

df['dropoff_hour']=df['dropoff'].dt.hour

df['dropoff_minute']=df['dropoff'].dt.minute

df['dropoff_second']=df['dropoff'].dt.second

df['dropoff_quarter']=df['dropoff'].dt.quarter

df

df.head

df.head()



df['dropoff_hour'].unique()



df['dropoff_month'].unique()

df['dropoff_year'].unique()

df['dropoff_dayname'].unique()

from scipy.stats import f_oneway

mon = df[df['dropoff_dayname'] == 'Monday']['tip']
tue = df[df['dropoff_dayname'] == 'Tuesday']['tip']
wed = df[df['dropoff_dayname'] == 'Wednesday']['tip']
thu = df[df['dropoff_dayname'] == 'Thursday']['tip']
fri = df[df['dropoff_dayname'] == 'Friday']['tip']
sat = df[df['dropoff_dayname'] == 'Saturday']['tip']
sun = df[df['dropoff_dayname'] == 'Sunday']['tip']

f_stat, p_val = f_oneway(mon, tue, wed, thu, fri, sat, sun)

print("ONE-WAY ANOVA (dropoff_dayname vs tip)")
print("F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Dropoff day has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Dropoff day has no impact on tip")

from scipy.stats import f_oneway

february_tips = df[df['dropoff_month'] == 'February']['tip']
march_tips = df[df['dropoff_month'] == 'March']['tip']
april_tips = df[df['dropoff_month'] == 'April']['tip']

f_stat, p_val = f_oneway(february_tips, march_tips, april_tips)

print("ONE-WAY ANOVA (dropoff_month vs tip)")
print("F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Dropoff month has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Dropoff month has no impact on tip")

from scipy.stats import f_oneway

q1 = df[df['dropoff_quarter'] == 1]['tip']
q2 = df[df['dropoff_quarter'] == 2]['tip']
q3 = df[df['dropoff_quarter'] == 3]['tip']
q4 = df[df['dropoff_quarter'] == 4]['tip']

f_stat, p_val = f_oneway(q1, q2, q3, q4)

print("ONE-WAY ANOVA (dropoff_quarter vs tip)")
print("F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Dropoff quarter has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Dropoff quarter has no impact on tip")

from scipy.stats import spearmanr

df['pickup_hour'] = df['pickup'].dt.hour

r, p_val = spearmanr(df['pickup_hour'], df['tip'])

print("SPEARMAN CORRELATION TEST (pickup_hour vs tip)")
print("Correlation:", r)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject Null Hypothesis")
    print("Pickup hour has impact on tip")
else:
    print("Accept Null Hypothesis")
    print("Pickup hour has no impact on tip")

from sklearn.preprocessing import *
le=LabelEncoder()
cat=['color','payment','pickup_zone', 'dropoff_zone','pickup_borough', 'dropoff_borough','dropoff_dayname','dropoff_year','dropoff_month','dropoff_borough','pickup_zone']
for i in cat :
  df[i]=le.fit_transform(df[i])

cont=['fare','tolls','total','distance']
from sklearn.preprocessing import *

st=StandardScaler()
df[cont]=st.fit_transform(df[cont])

columns_to_drop = [
    'pickup',
    'dropoff',
    'pickup_zone',
    'dropoff_zone',
    'pickup_borough',
    'dropoff_borough',
    'dropoff_month',
    'dropoff_year',
    'dropoff_dayname',
    'dropoff_hor', # Including this as it appeared in df.info(), likely a typo
    'dropoff_hour',
    'dropoff_minute',
    'dropoff_second',
    'dropoff_quarter'
]

# Filter out columns that do not exist in the DataFrame
existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]

df = df.drop(columns=existing_columns_to_drop)

x=df.drop('tip',axis=1)
y=df.tip

x.shape
y.shape

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train

df.info()

from sklearn.linear_model import LinearRegression
from sklearn.metrics import *
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mean_squared_error(y_test,y_pred)