# -*- coding: utf-8 -*-
"""gitt1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPaPFREg9e5J6Ssy6vpXxhR6Gxb75d0J
"""

import seaborn as sns
df=sns.load_dataset("taxis")
print(df.head(20))
print(df.shape)
print(df.info())
print(df.describe())

df.isnull().sum()

df1=df.copy()

import pandas as pd
df[df['pickup_zone'].isnull()]

df['pickup_zone']=df['pickup_zone'].dropna()



df['pickup_zone'].isnull().sum()

df.isnull().sum()



df.dropna(subset=['pickup_zone'])



df.isnull().sum()

df=df.dropna(subset=['pickup_zone'])

df.isnull().sum()

df=df.dropna(subset=['dropoff_zone','dropoff_borough'])

df.isnull().sum()

df.reset_index(drop=True)

#eda
#tip is target col
#tip is numerical feature ,analysize with color feature which is categorical

df.color.value_counts()

from numpy import std
#graphical analysis
sns.barplot(x=df.color,y=df.tip,estimator=std)

from numpy import std
#graphical analysis
sns.barplot(x=df.color,y=df.tip)

df.color.value_counts()

sns.histplot(df.color,kde=True)

import pandas as pd
import matplotlib.pyplot as plt

# Select only numeric columns (important!)
correlation_matrix = df.select_dtypes(include='number').corr()

# Plot correlation matrix
plt.figure(figsize=(10, 8))
plt.imshow(correlation_matrix)
plt.colorbar()

plt.xticks(range(len(correlation_matrix.columns)),
           correlation_matrix.columns, rotation=90)
plt.yticks(range(len(correlation_matrix.columns)),
           correlation_matrix.columns)

plt.title("Correlation Matrix for Taxi Dataset")
plt.tight_layout()
plt.show()

'''
barplot-insights
1.yellow taxis receive higher tips compared to green taxi
2.this shows taxi color has influence on tip

hinstogram insights
1.the frequency of tips is much higher for yellow taxi
2.green taxis show very few tip occurrences in comparison

'''

'''H0:distribution of tip for yellow
H1:didtribution of tip !=distribution of tip of green
'''



yellow_tip=df['tip'][df['color']=='yellow']

green_tip=df['tip'][df['color']=='green']

yellow_tip.shape

