# -*- coding: utf-8 -*-
"""kmeansclustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzsLZiIeUnwMe7KSb6kYJdbJ3TLW3khX
"""

from google.colab import drive
import pandas as pd


drive.mount('/content/drive')


df = pd.read_csv('/content/Mall_Customers.csv')
df.head()

df.isnull().sum()

df.dtypes

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Genre']=le.fit_transform(df['Genre'])
df.head()

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11) :
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=0)
  kmeans.fit(x)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)
plt.title("The elbow method")
plt.xlabel("no of clusters")
plt.ylabel("wcss")
plt.show()

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=0)

X = x.iloc[:, [2, 3]].values
y_kmeans = kmeans.fit_predict(X)

# Plot clusters
plt.scatter(X[y_kmeans == 0, 0], X[y_kmeans == 0, 1],
            s=100, c='red', label='Cluster 1')

plt.scatter(X[y_kmeans == 1, 0], X[y_kmeans == 1, 1],
            s=100, c='blue', label='Cluster 2')

plt.scatter(X[y_kmeans == 2, 0], X[y_kmeans == 2, 1],
            s=100, c='green', label='Cluster 3')

plt.scatter(X[y_kmeans == 3, 0], X[y_kmeans == 3, 1],
            s=100, c='cyan', label='Cluster 4')

plt.scatter(X[y_kmeans == 4, 0], X[y_kmeans == 4, 1],
            s=100, c='magenta', label='Cluster 5')

# Plot centroids
plt.scatter(kmeans.cluster_centers_[:, 0],
            kmeans.cluster_centers_[:, 1],
            s=300, c='yellow', label='Centroids')

plt.title('Clusters of Customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')