# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zwxITq1Pl6xtGrqlkutgN9FvlOaZm7sx
"""

from google.colab import drive
import pandas as pd


drive.mount('/content/drive')


df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

df.isnull().sum()

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
x=df[['Age','Purchased']]
y=df['EstimatedSalary']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model1=KNeighborsRegressor()
model2=LinearRegression()
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)

print(mean_squared_error(y_test,y_pred1)**0.5)
print(mean_squared_error(y_test,y_pred2)**0.5)