# -*- coding: utf-8 -*-
"""Untitled52.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_ptjJCYt54nXjqMk8BJ1_T2WsfjbA7u
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

iris=load_iris()
x=iris.data
y=iris.target

x_scaled=StandardScaler().fit_transform(x)
x_scaled.shape



"""Apply pca
# New Section
"""

pca=PCA()
x_pca=pca.fit_transform(x_scaled)

plt.figure()
plt.plot(range(1,len(pca.explained_variance_ratio_)+1),pca.explained_variance_ratio_)
plt.plot(range(1,len(pca.explained_variance_ratio_)+1),np.cumsum(pca.explained_variance_ratio_))
plt.grid(True)
plt.show()

pca_2d=PCA(n_components=2)
x_2d=pca_2d.fit_transform(x_scaled)
sns.scatterplot(x=x_2d[:,0],y=x_2d[:,1],hue=iris.target_names[y],palette='tab10')

import kagglehub
import pandas as pd
import os

# Download dataset
path = kagglehub.dataset_download("imakash3011/customer-personality-analysis")
print("Path to dataset files:", path)

# List files in the dataset folder
print(os.listdir(path))

# Load the CSV file (usually named marketing_campaign.csv)
df = pd.read_csv(os.path.join(path, "marketing_campaign.csv"), sep="\t")

# Show first 5 rows
df.head()

df.isnull().sum()

df.dtypes

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Education']=le.fit_transform(df['Education'])

df.head()

df['Marital_Status']=le.fit_transform(df['Marital_Status'])
df=df.drop(columns=['ID'])

df.head()

df=df.dropna(subset=['Income'])

df.isnull().sum()

print(df.head())

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
x_train,x_test,y_trssian,y_test=train_test_split()
col=['Year_Birth','Income','MntWines','MntFruits']