# -*- coding: utf-8 -*-
"""svm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BMefrypDz1uJpViMvYZoaq2pE_OZuwg
"""

from google.colab import drive

import pandas as pd




drive.mount('/content/drive')




df = pd.read_csv('/content/heart (1).csv')

print(df.head())

df.head()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
df.dropna(inplace=True)
label_encoders={}
for col in df.select_dtypes(include=['object']).columns :
  le=LabelEncoder()
  df[col]=le.fit_transform(df[col])
  label_encoders[col]=le

x=df.drop(columns=['target'])
y=df['target']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

from sklearn.svm import SVC
svm_linear=SVC(kernel='poly',C=1)
svm_linear.fit(x_train,y_train)
y_pred_linear=svm_linear.predict(x_test)

from sklearn.metrics import *
accuracy_score(y_test,y_pred_linear)

confusion_matrix(y_test,y_pred_linear)

print(classification_report(y_test,y_pred_linear))

import kagglehub
import pandas as pd
import os

# Download latest version
path = kagglehub.dataset_download(
    "altruistdelhite04/loan-prediction-problem-dataset"
    )

print("Path to dataset files:", path)

# List files inside the dataset folder
print(os.listdir(path))

# Load CSV file (usually named train.csv)
df = pd.read_csv(os.path.join(path, "train_u6lujuX_CVtuZ9i.csv"))

# Display first 5 rows
print(df.head())

df.head()

df=df.drop(columns=['Loan_ID'])

df.head()

df.isnull().sum()

df['Married']=df['Married'].fillna(df['Married'].mode()[0])

df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])

df['Loan_Status']=le.fit_transform(df['Loan_Status'])

df['Self_Employed']=df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

df['Loan_Amount_Term']=df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0])

df = df.dropna(subset=['LoanAmount'])

df.isnull().sum()

df.isnull().sum()



df['Credit_History'].unique()

df['Dependents']=df['Dependents'].fillna(df['Dependents'].mode()[0])

df['Credit_History']=df['Credit_History'].fillna(df['Credit_History'].mode()[0])

df.dtypes

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Married']=le.fit_transform(df['Married'])
df['Gender']=le.fit_transform(df['Gender'])

df.head()

df['Education']=le.fit_transform(df['Education'])
lst=['Self_Employed','Property_Area']
for col in lst:
  df[col]=le.fit_transform(df[col])

df.head()



float_to_int_cols = ['CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']
for col in float_to_int_cols:
    df[col] = df[col].astype(int)

print(df.dtypes)

print(df.head(10))

df['Dependents'].unique()



df['Dependents']=df['Dependents'].replace({'3+':3,'1':1,'0':0,'2':2}).astype(int)

df.dtypes

df.head()

sc=StandardScaler()

x=df.drop(columns=['Loan_Status'])
y=df['Loan_Status']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

ls=['ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term']
x_train[ls]=sc.fit_transform(x_train[ls])
x_test[ls]=sc.transform(x_test[ls])

x_train

from sklearn.svm import SVC
model=SVC(kernel='rbf',C=1,gamma='scale')
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
m=accuracy_score(y_test,y_pred)
print(accuracy_score(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')

print(confusion_matrix(y_test,y_pred))

from sklearn.svm import SVC
model=SVC(kernel='linear',C=1,gamma='scale')
model.fit(x_train,y_train)
n=accuracy_score(y_test,y_pred)

y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')

print(confusion_matrix(y_test,y_pred))

from sklearn.svm import SVC
model=SVC(kernel='poly',C=1,gamma='scale')
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))
print('\n')
o=accuracy_score(y_test,y_pred)

print(confusion_matrix(y_test,y_pred))

from matplotlib import pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

model_rbf = SVC(kernel='rbf', C=1, gamma='scale')
model_rbf.fit(x_train, y_train)
y_pred_rbf = model_rbf.predict(x_test)
m = accuracy_score(y_test, y_pred_rbf)

model_linear = SVC(kernel='linear', C=1, gamma='scale')
model_linear.fit(x_train, y_train)
y_pred_linear_calc = model_linear.predict(x_test)
n = accuracy_score(y_test, y_pred_linear_calc)

model_poly = SVC(kernel='poly', C=1, gamma='scale')
model_poly.fit(x_train, y_train)
y_pred_poly_calc = model_poly.predict(x_test)
o = accuracy_score(y_test, y_pred_poly_calc)

kernels = ['RBF', 'Linear', 'Poly']
accuracies = [m, n, o]

plt.figure(figsize=(8, 5))
plt.bar(kernels, accuracies, color=['skyblue', 'lightcoral', 'lightgreen'])
plt.xlabel('SVM Kernel')
plt.ylabel('Accuracy Score')
plt.title('Accuracy of SVM Models with Different Kernels')
plt.ylim(min(accuracies) * 0.95, max(accuracies) * 1.05)
for i, accuracy in enumerate(accuracies):
    plt.text(i, accuracy, f'{accuracy:.4f}', ha='center', va='bottom')
plt.show()

print(f"RBF Kernel Accuracy: {m:.4f}")
print(f"Linear Kernel Accuracy: {n:.4f}")
print(f"Polynomial Kernel Accuracy: {o:.4f}")