# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lv9Jbqyf4ukjcOZTRbPIyNNDkmLqRljh
"""

import seaborn as sns
import numpy as np
import pandas as pd

df=sns.load_dataset("taxis")

print(df.head(20))



df=df.dropna(subset=['payment'])

df['payment'].unique()

credit=df[df['payment']=='credit card']['tip']

credit

cash=df[df['payment']=='cash']['tip']

cash

#barplot
import matplotlib.pyplot as plt
plt.bar(["credit","cash"],[credit.mean(),cash.mean()])
plt.show()

import matplotlib.pyplot as plt

plt.hist(credit, bins=30, alpha=0.5, label='Credit Card')
plt.hist(cash, bins=30, alpha=0.5, label='Cash')

plt.axvline(credit.mean())
plt.axvline(cash.mean())

plt.title("Tip Distribution")
plt.xlabel("Tip Amount")
plt.legend()
plt.show()

from scipy.stats import ttest_ind
t_stat, p_value = ttest_ind(credit, cash)

print("T-statistic:", t_stat)
print("P-value:", p_value)

alpha = 0.05
if p_value <= alpha:
    print("Reject Null Hypothesis: Payment method affects tip amount.")
else:
    print("Fail to Reject Null Hypothesis: No significant difference.")

import pandas as pd
from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df_clean = df[['dropoff_borough', 'tip']].dropna()


boroughs = df_clean['dropoff_borough'].unique()

groups = [
    df_clean[df_clean['dropoff_borough'] == b]['tip']
        for b in boroughs
]


f_stat, p_value = f_oneway(*groups)

print("ONE-WAY ANOVA RESULT")
print("F-statistic:", f_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Result: Reject H0 (Significant difference exists)")
else:
    print("Result: Fail to Reject H0 (No significant difference)")


tukey = pairwise_tukeyhsd(
    endog=df_clean['tip'],
    groups=df_clean['dropoff_borough'],
    alpha=0.05
)

print("\nTUKEY HSD RESULT")
print(tukey)

import pandas as pd
from scipy.stats import f_oneway

# Example: Group data by pickup_zone
groups = [group["tip"].values for name, group in df.groupby("pickup_zone")]

# Perform one-way ANOVA
anova_result = f_oneway(*groups)

print("F-statistic:", anova_result.statistic)
print("p-value:", anova_result.pvalue)

if anova_result.pvalue < 0.05:
    print("Significant difference exists between pickup zones.")
else:
    print("No significant difference between pickup zones.")

import pandas as pd
from scipy.stats import f_oneway

# Group data by dropoff_zone
groups = [group["tip"].values for name, group in df.groupby("dropoff_zone")]

# Perform one-way ANOVA
anova_result = f_oneway(*groups)

print("F-statistic:", anova_result.statistic)
print("p-value:", anova_result.pvalue)

if anova_result.pvalue < 0.05:
    print("Significant difference exists between dropoff zones.")
else:
    print("No significant difference between dropoff zones.")

